config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "signup" => "users#new", as: :signup
  post "api/register" => "users#create", defaults: { format: :json }, as: :register
  get "signin" => "sessions#new", as: :login
  post "api/login" => "sessions#create", defaults: { format: :json }
  get "signout" => "sessions#destroy", as: :logout
  delete "api/logout" => "sessions#destroy", defaults: { format: :json }
  get "upload" => "uploads#new", as: :upload_file
  post "upload/file" => "uploads#create", as: :file
  post "api/upload/file" => "uploads#create", defaults: { format: :json }
  post "upload" => "uploads#new"
  get "files" => "uploads#index"
  get "api/files" => "uploads#index", defaults: { format: :json }
  delete "files/delete/:file_id" => "uploads#destroy", as: :user_file_delete
  delete "api/files/delete/:file_id" => "uploads#destroy", defaults: { format: :json }
  post "api/file/download/:user_id/:file_id" => "uploads#download", defaults: { format: :json }
  get "file/download/:user_id/:file_id" => "uploads#download", as: :user_download_option
  get "files/view/:user_id/:file_id" => "uploads#show", as: :user_view
  get "api/files/view/:user_id/:file_id" => "uploads#show", defaults: { format: :json }
  post "files/update/:file_id" => "uploads#update", as: :update_public
  put "api/files/update/:file_id" => "uploads#update", defaults: { format: :json }

  resources :users, only: [ :new, :create ]
  resources :sessions, only: [ :new, :create ]

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "uploads#index"
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  validates :name, uniqueness: true, presence: true
  validates :file_path, presence: true

  def delete_upload
    if File.exist?(self.file_path)
      File.delete(self.file_path)
      true
    else
      false
    end
  end

  def read_text_content
    (raise StandardError) unless self.content_type == "text/plain"
    File.read(self.file_path)
  rescue StandardError => e
    Rails.logger.error "Error reading file: #{e.message}"
    "Unable to Preview"
  end

  def self.convert_size(size_in_bytes)
    if size_in_bytes < 1024
      "#{size_in_bytes} bytes"
    elsif size_in_bytes < 1024 * 1024
      "#{(size_in_bytes / 1024.0).round(2)} KB"
    else
      "#{(size_in_bytes / (1024.0 * 1024.0)).round(2)} MB"
    end
  end

  def self.save_locally(uploaded_file, login_user_id)
    save_path = Rails.root.join("public", "uploads", login_user_id)
    FileUtils.mkdir_p(save_path) unless File.directory?(save_path)
    file_name = uploaded_file.original_filename
    base_name = File.basename(file_name, ".*")
    extension = File.extname(file_name)
    timestamp = Time.now.strftime("%Y%m%d%H%M%S")
    new_file_name = "#{base_name}_#{timestamp}#{extension}"
    file_path = File.join(save_path, new_file_name)
    File.open(file_path, "wb") do |file|
      file.write(uploaded_file.read)
    end
    file_size = Upload.convert_size uploaded_file.size
    [ file_path, new_file_name, file_size, uploaded_file.content_type ]
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user, except: [ :show, :download ]

  def new
    @upload = Upload.new
  end

  def create
    begin
      uploaded_file = file_params[:file]
      (raise ActiveRecord::ParameterMissing, "Upload file") if uploaded_file.blank?
      file_path, file_name, file_size, content_type = Upload.save_locally(uploaded_file, logged_in_user.id.to_s)
      @upload = logged_in_user.uploads.new({
        name: file_name,
        file_path: file_path,
        size: file_size,
        is_public: file_params[:is_public].nil? ? false : file_params[:is_public],
        content_type: content_type
      })
      respond_to do |format|
        if @upload.save
          format.html { redirect_to "/", notice: "File uploaded successfully." }
          format.json { render json: { message: "File uploaded successfully.", upload: @upload }, status: :created }
        else raise StandardError, "Unable to upload file"         end
      end
    rescue ActionController::ParameterMissing => e
      handle_error(e.message, :bad_request)
    rescue ActiveRecord::RecordNotFound => e
      handle_error(e.message, :bad_request)
    rescue StandardError => e
      handle_error(e.message, :unprocessable_entity)
    end
  end

  def index
    @files = logged_in_user.uploads.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.json { render json: { files: @files } }
    end
  end

  def update
    begin
      (raise ActionController::ParameterMissing, "fileId and is_public_updated are required.") if file_params[:is_public_updated].blank? || params[:file_id].blank?
      file = logged_in_user.uploads.find_by(id: params[:file_id])
      if file
        is_public = file_params[:is_public_updated].to_i == 1 ? true : false
        file.update(is_public: is_public)
        respond_to do |format|
          format.html { redirect_to "/", notice: "File visibility updated successfully." }
          format.json { render json: { status: "Success" } }
        end
      else raise ActiveRecord::RecordNotFound, "File not found"       end
    end
  rescue ActiveRecord::RecordNotFound => e
    handle_error(e.message, :bad_request)
  rescue ActionController::ParameterMissing => e
    handle_error(e.message, :bad_request)
  rescue StandardError => e
    handle_error(e.message, :unauthorized)
  end

  def destroy
    begin
    permitted_params = params.permit(:file_id)
    (raise ActionController::ParameterMissing, "fileId is required.") if permitted_params[:file_id].blank?
    file_id = permitted_params[:file_id]
    file = logged_in_user.uploads.find_by!(id: file_id)
    (raise ActiveRecord::RecordNotFound, "File not found") unless File.exist?(file.file_path)
    respond_to do |format|
      ActiveRecord::Base.transaction do
        file.destroy!
        raise ActiveRecord::RecordNotFound, "Unable to delete" unless file.delete_upload
      end
      format.html { redirect_to "/", notice: "File deleted successfully." }
      format.json { render json: { status: "Success" } }
      end
    end
  rescue ActiveRecord::RecordNotFound => e
    handle_error(e.message, :bad_request)
  rescue ActionController::ParameterMissing => e
    handle_error(e.message, :bad_request)
  rescue StandardError => e
    handle_error(e.message, :unauthorized)
  end

  def show
    begin
      user_id = params[:user_id]
      (raise ActionController::ParameterMissing, "UserId and fileId are required.") if params[:file_id].blank? || params[:user_id].blank?
      @file_owner = User.find_by(id: user_id)
      (raise StandardError, "Not able to access file") unless @file_owner
      @file = @file_owner.uploads.find_by(id: params[:file_id])
      if @file.present? && File.exist?(@file.file_path) && @file.is_public == true
        @relative_file_path = @file.file_path.sub(Rails.root.join("public").to_s, "")
        @file_content = @file.read_text_content if @file.content_type == "text/plain"
        respond_to do |format|
          format.html
          format.json { render json: { file: @file } }
        end
      else raise ActiveRecord::RecordNotFound, "File not found"       end
    end
  rescue ActiveRecord::RecordNotFound => e
    handle_error(e.message, :bad_request)
  rescue ActionController::ParameterMissing => e
    handle_error(e.message, :bad_request)
  rescue StandardError => e
    handle_error(e.message, :unauthorized)
  end

  def download
    begin
      (raise ActionController::ParameterMissing, "UserId and fileId are required.") if params[:file_id].blank? || params[:user_id].blank?
      user_id = params[:user_id]
      @file_owner = User.find_by(id: user_id)
      (raise StandardError, "Not able to access file") unless @file_owner
      @file = @file_owner.uploads.find_by(id: params[:file_id])
      file_path = @file.file_path
      if @file.present? && File.exist?(file_path) && (@file.is_public == true)
        send_upload_securely @file
      else raise ActiveRecord::RecordNotFound, "File not found.... Only Public files can be downloaded"       end
    end
  rescue ActiveRecord::RecordNotFound => e
    handle_error(e.message, :bad_request)
  rescue ActionController::ParameterMissing => e
    handle_error(e.message, :bad_request)
  rescue StandardError => e
    handle_error(e.message, :unauthorized)
  end

  private

  def send_upload_securely(upload)
    original_filename = File.basename(upload.file_path)
    extension = File.extname(original_filename)
    safe_filename = "#{SecureRandom.hex(8)}#{extension}"
    send_data File.read(upload.file_path), # Not in model because this is a controller method
      filename: safe_filename,
      disposition: "attachment"
  end

  def file_params
    params.require(:upload).permit(:file, :is_public, :file_id, :user_id, :is_public_updated)
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/index.html.erb
<div class="container mt-5 pt-5">
    <h1 class="text-center">File Dashboard - <%= @files.count %> files</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Upload Date</th>
          <th>Size</th>
          <th>Actions</th>
          <th>Sharing</th>
        </tr>
      </thead>
      <tbody>
        <% @files.each do |file| %>
          <tr>
            <td><%= file.name %></td>
            <td><%= file.created_at.strftime("%d %B %Y") %></td>
            <td><%= file.size %></td>
            <td>
                <% if file.is_public %>
                <%= link_to 'Download', user_download_option_path(user_id: logged_in_user.id, file_id: file.id), method: :post, class: 'btn btn-primary btn-sm' %>
                <% end %>
              <%= button_to 'Delete', user_file_delete_path(user_id: logged_in_user.id, file_id: file.id), 
               method: :delete, 
               onclick: "return confirm('Are you sure you want to delete this file?') ? true : false;",
               class: 'btn btn-danger btn-sm' %>
    </td>
            </td>
            <td>
              <div class="form-check form-switch">
                <%= form_for :upload, url: update_public_path(file.id), html: { class: 'form-inline' } do |f| %>
                    <%= f.check_box :is_public_updated, checked: file.is_public, class: "custom-class", 
                        onchange: "event.stopPropagation(); if(!confirm('Are you sure you want to change the visibility of this file?')) { this.checked = !this.checked; } else { this.form.submit(); }" %>
                <% end %>
                <% if file.is_public %>
                    <label class="form-check-label" for="sharingSwitch<%= file.id %>">
                    <%= link_to 'Link', user_view_path(user_id: logged_in_user.id, file_id: file.id), target: '_blank', class: 'file-link' %>
                    </label>
                <% else %>
                    Private File
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="text-center mt-4">
      <%= link_to 'Upload Files', upload_file_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/uploads/new.html.erb
<div class="container mt-5">
    <%= form_for :upload, url: file_path, html: { multipart: true } do |form| %>

        <div class="mb-3 mt-4 pt-4">
            <%= form.label :file, "Upload File" %>
            <%= form.file_field :file, class: "form-control", required: true%>
        </div>

        <div class="form-group mb-3  row align-items-center">
            <div class="col">
                <div class="form-check">
                    <%= form.check_box :is_public, { class: "form-check-input" }, true, false %>
                    <%= form.label :is_public, "Is Public?", class: "form-check-label" %>
                </div>
            </div>
        </div>

        <%= form.submit "Upload File", class: "btn btn-success btn-lg btn-block", data: { disable_with: "Uploading..." } %>

    <% end %>
</div>

app/views/uploads/show.html.erb
<div class="container mt-5 pt-4">
    <h1>File Details</h1>
  
    <p><strong>File Name:</strong> <%= @file.name %></p>
    <p><strong>File Type:</strong> <%= @file.content_type %></p>
    <p><strong>File Size:</strong> <%= @file.size %></p>
    <p><strong>File Owner:</strong> <%= @file_owner.username %></p>
  
    <div class="file-content">
      <% case @file.content_type %>
      <% when 'text/plain' %>
        <h2>File Content:</h2>
        <pre><%= @file_content%></pre>
      <% when 'image/jpeg', 'image/png', 'image/gif' %>
        <h2>Image Preview:</h2>
        <div class="image-preview mb-4">
            <%= image_tag @relative_file_path, class: "img-fluid img-thumbnail", alt: "Uploaded Image" %>
          </div>
      <% else %>
        <p>File type not supported for preview.</p>
        <%= link_to 'Download File', user_download_option_path(user_id: @file_owner.id, file_id: @file.id), class: 'btn btn-primary', download: true %>
      <% end %>
    </div>
  </div>
  